language: objective-c
osx_image: xcode6.4
cache: bundler
rvm:
  - system
before_install:
  - sudo gem install bundler
  - sudo gem install xcode-install
install:
  - xcode-install install '7 beta 5'
  - bundle install
script:
  - bundle exec fastlane test
after_success:
  - bundle exec fastlane coverage
  - bash <(curl -s https://codecov.io/bash)
